//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPicasa {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPicasa.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOOGLE ACCOUNT.
        /// </summary>
        internal static string account_str {
            get {
                return ResourceManager.GetString("account_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album has been downloaded!.
        /// </summary>
        internal static string albdwn_str {
            get {
                return ResourceManager.GetString("albdwn_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All my albums.
        /// </summary>
        internal static string albums_str {
            get {
                return ResourceManager.GetString("albums_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MobiPicasa.
        /// </summary>
        internal static string appname {
            get {
                return ResourceManager.GetString("appname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Take Photo.
        /// </summary>
        internal static string camerabtn {
            get {
                return ResourceManager.GetString("camerabtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        internal static string cancel {
            get {
                return ResourceManager.GetString("cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured image has been saved successfully!.
        /// </summary>
        internal static string capture_done {
            get {
                return ResourceManager.GetString("capture_done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album {0} : Image {1} of {2}.
        /// </summary>
        internal static string currentimg {
            get {
                return ResourceManager.GetString("currentimg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MMM dd, yyyy.
        /// </summary>
        internal static string date_str {
            get {
                return ResourceManager.GetString("date_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string downloadbtn {
            get {
                return ResourceManager.GetString("downloadbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email:.
        /// </summary>
        internal static string email_str {
            get {
                return ResourceManager.GetString("email_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get albums data from Picasa server!.
        /// </summary>
        internal static string error_albums {
            get {
                return ResourceManager.GetString("error_albums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get authentication from google. Check your email and password and also your network connection!.
        /// </summary>
        internal static string error_auth {
            get {
                return ResourceManager.GetString("error_auth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not load images from Picasa server!.
        /// </summary>
        internal static string error_load {
            get {
                return ResourceManager.GetString("error_load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string loading_str {
            get {
                return ResourceManager.GetString("loading_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location: .
        /// </summary>
        internal static string location_str {
            get {
                return ResourceManager.GetString("location_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string login_str {
            get {
                return ResourceManager.GetString("login_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string loginbtn_str {
            get {
                return ResourceManager.GetString("loginbtn_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to Log Out?.
        /// </summary>
        internal static string logout_msg {
            get {
                return ResourceManager.GetString("logout_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string logoutbtn {
            get {
                return ResourceManager.GetString("logoutbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No album name.
        /// </summary>
        internal static string noalbum {
            get {
                return ResourceManager.GetString("noalbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo has been downloaded.
        /// </summary>
        internal static string picdwn_str {
            get {
                return ResourceManager.GetString("picdwn_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pictures.
        /// </summary>
        internal static string picture_str {
            get {
                return ResourceManager.GetString("picture_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play.
        /// </summary>
        internal static string playbtn {
            get {
                return ResourceManager.GetString("playbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        internal static string pwd_str {
            get {
                return ResourceManager.GetString("pwd_str", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Password.
        /// </summary>
        internal static string save_pwd {
            get {
                return ResourceManager.GetString("save_pwd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        internal static string stopbtn {
            get {
                return ResourceManager.GetString("stopbtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string uploadbtn {
            get {
                return ResourceManager.GetString("uploadbtn", resourceCulture);
            }
        }
    }
}
